#ifndef DB_ERROR_CODE
#define DB_ERROR_CODE
#define SUCCESS 0
#define DB_SUCCESS 0
#define DB_CONNECT_FAILED 0x101
#define DB_CONNECT_CLOSED 0x102
#define DB_CLOSED  1
#define DB_EXECUTE_FAILED 0x201
#define DB_CONDITION_ERROR 0x400
#define DB_NOT_RUN_QUERY  0x500
#define DB_NOT_FOUND_RECORD 0x600


#endif
